apiVersion: v1alpha1
kind: ClusterValidator
metadata:
  name: field-validation
spec:
  configuration:
    # global test configuration
    successThreshold: 10
    failureThreshold: 10 
    interval: 1s
  resources:
    # resource name and apiVersion
  - name: namespaces
    apiVersion: v1
    # scope of resources
    names:
      include: 
      - "*"
    # define the jsonpath and value as a test condition
    fields: 
      # you can also use JSONPath notation here according to https://kubernetes.io/docs/reference/kubectl/jsonpath
    - path: .status.phase
      values:
      # values considered to be correct (OR condition)
      - active
    required: true
