apiVersion: v1alpha1
kind: ClusterValidator
metadata:
  name: field-validation
spec:
  configuration:
    successThreshold: 3
    failureThreshold: 3 
    interval: 1ms
  endpoints:
    cluster:
    - name: ETCD Validation
      uri: "/readyz?include=etcd&verbose"
      required: true