name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    if: github.repository_owner == 'keikoproj'
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    # Authenticate to DockerHub first to reduce rate limiting
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test
      run: |
        go test -v ./... -coverprofile ./coverage.txt
        make docker-build

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt